// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OriCafe.Models;

#nullable disable

namespace OriCafe.Migrations
{
    [DbContext(typeof(OriCafeContext))]
    [Migration("20240414064559_UpdateGiaGoc")]
    partial class UpdateGiaGoc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OriCafe.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double>("GiaBan")
                        .HasColumnType("float")
                        .HasColumnName("gia_ban");

                    b.Property<int?>("IdHoaDon")
                        .HasColumnType("int")
                        .HasColumnName("id_hoa_don");

                    b.Property<int?>("IdSanPham")
                        .HasColumnType("int")
                        .HasColumnName("id_san_pham");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.HasKey("Id")
                        .HasName("PK__Chi_Tiet__3213E83F7838515E");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdSanPham");

                    b.ToTable("Chi_Tiet_Hoa_Don", (string)null);
                });

            modelBuilder.Entity("OriCafe.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int")
                        .HasColumnName("id_khach_hang");

                    b.Property<int?>("IdNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("id_nhan_vien");

                    b.Property<int?>("IdQuan")
                        .HasColumnType("int")
                        .HasColumnName("id_quan");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao");

                    b.Property<int>("TongTien")
                        .HasColumnType("int")
                        .HasColumnName("tong_tien");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__Hoa_Don__3213E83FA4CC0DC5");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("IdQuan");

                    b.ToTable("Hoa_Don", (string)null);
                });

            modelBuilder.Entity("OriCafe.Models.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dia_chi");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int")
                        .HasColumnName("diem_tich_luy");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("dien_thoai");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int?>("IdQuan")
                        .HasColumnType("int")
                        .HasColumnName("id_quan");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_khach_hang");

                    b.HasKey("Id")
                        .HasName("PK__Khach_Ha__3213E83F026668A9");

                    b.HasIndex("IdQuan");

                    b.ToTable("Khach_Hang", (string)null);
                });

            modelBuilder.Entity("OriCafe.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdQuan")
                        .HasColumnType("int")
                        .HasColumnName("id_quan");

                    b.Property<string>("TenLoaiSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_loai_san_pham");

                    b.HasKey("Id")
                        .HasName("PK__Loai_San__3213E83FD369CAF2");

                    b.HasIndex("IdQuan");

                    b.ToTable("Loai_San_Pham", (string)null);
                });

            modelBuilder.Entity("OriCafe.Models.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("dien_thoai");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int?>("IdQuan")
                        .HasColumnType("int")
                        .HasColumnName("id_quan");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_nhan_vien");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__Nhan_Vie__3213E83FA07ABEBA");

                    b.HasIndex("IdQuan");

                    b.ToTable("Nhan_Vien", (string)null);
                });

            modelBuilder.Entity("OriCafe.Models.PhanQuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdQuyenHan")
                        .HasColumnType("int")
                        .HasColumnName("id_quyen_han");

                    b.Property<int?>("IdTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("id_tai_khoan");

                    b.HasKey("Id")
                        .HasName("PK__Phan_Quy__3213E83F61BE7027");

                    b.HasIndex("IdQuyenHan");

                    b.HasIndex("IdTaiKhoan");

                    b.ToTable("Phan_Quyen", (string)null);
                });

            modelBuilder.Entity("OriCafe.Models.QuanCaPhe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("dien_thoai");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("TenQuan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_quan");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__Quan_Ca___3213E83FB31B1790");

                    b.ToTable("Quan_Ca_Phe", (string)null);
                });

            modelBuilder.Entity("OriCafe.Models.QuyenHan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenQuyenHan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_quyen_han");

                    b.HasKey("Id")
                        .HasName("PK__Quyen_Ha__3213E83FA8787227");

                    b.ToTable("Quyen_Han", (string)null);
                });

            modelBuilder.Entity("OriCafe.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double>("GiaBan")
                        .HasColumnType("float")
                        .HasColumnName("gia_ban");

                    b.Property<double>("GiaGoc")
                        .HasColumnType("float");

                    b.Property<int?>("IdLoaiSanPham")
                        .HasColumnType("int")
                        .HasColumnName("id_loai_san_pham");

                    b.Property<int?>("IdQuan")
                        .HasColumnType("int")
                        .HasColumnName("id_quan");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_san_pham");

                    b.HasKey("Id")
                        .HasName("PK__San_Pham__3213E83FC7304E05");

                    b.HasIndex("IdLoaiSanPham");

                    b.HasIndex("IdQuan");

                    b.ToTable("San_Pham", (string)null);
                });

            modelBuilder.Entity("OriCafe.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("id_nhan_vien");

                    b.Property<int?>("IdQuan")
                        .HasColumnType("int")
                        .HasColumnName("id_quan");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mat_khau");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_tai_khoan");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int")
                        .HasColumnName("vai_tro");

                    b.HasKey("Id")
                        .HasName("PK__Tai_Khoa__3213E83FACED733D");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("IdQuan");

                    b.ToTable("Tai_Khoan", (string)null);
                });

            modelBuilder.Entity("OriCafe.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("OriCafe.Models.HoaDon", "IdHoaDonNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("IdHoaDon")
                        .HasConstraintName("FK__Chi_Tiet___id_ho__5CD6CB2B");

                    b.HasOne("OriCafe.Models.SanPham", "IdSanPhamNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("IdSanPham")
                        .HasConstraintName("FK__Chi_Tiet___id_sa__5DCAEF64");

                    b.Navigation("IdHoaDonNavigation");

                    b.Navigation("IdSanPhamNavigation");
                });

            modelBuilder.Entity("OriCafe.Models.HoaDon", b =>
                {
                    b.HasOne("OriCafe.Models.KhachHang", "IdKhachHangNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdKhachHang")
                        .HasConstraintName("FK__Hoa_Don__id_khac__59063A47");

                    b.HasOne("OriCafe.Models.NhanVien", "IdNhanVienNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNhanVien")
                        .HasConstraintName("FK__Hoa_Don__id_nhan__5812160E");

                    b.HasOne("OriCafe.Models.QuanCaPhe", "IdQuanNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdQuan")
                        .HasConstraintName("FK__Hoa_Don__id_quan__59FA5E80");

                    b.Navigation("IdKhachHangNavigation");

                    b.Navigation("IdNhanVienNavigation");

                    b.Navigation("IdQuanNavigation");
                });

            modelBuilder.Entity("OriCafe.Models.KhachHang", b =>
                {
                    b.HasOne("OriCafe.Models.QuanCaPhe", "IdQuanNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("IdQuan")
                        .HasConstraintName("FK__Khach_Han__id_qu__4E88ABD4");

                    b.Navigation("IdQuanNavigation");
                });

            modelBuilder.Entity("OriCafe.Models.LoaiSanPham", b =>
                {
                    b.HasOne("OriCafe.Models.QuanCaPhe", "IdQuanNavigation")
                        .WithMany("LoaiSanPhams")
                        .HasForeignKey("IdQuan")
                        .HasConstraintName("FK__Loai_San___id_qu__5165187F");

                    b.Navigation("IdQuanNavigation");
                });

            modelBuilder.Entity("OriCafe.Models.NhanVien", b =>
                {
                    b.HasOne("OriCafe.Models.QuanCaPhe", "IdQuanNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdQuan")
                        .HasConstraintName("FK__Nhan_Vien__id_qu__4BAC3F29");

                    b.Navigation("IdQuanNavigation");
                });

            modelBuilder.Entity("OriCafe.Models.PhanQuyen", b =>
                {
                    b.HasOne("OriCafe.Models.QuyenHan", "IdQuyenHanNavigation")
                        .WithMany("PhanQuyens")
                        .HasForeignKey("IdQuyenHan")
                        .HasConstraintName("FK__Phan_Quye__id_qu__6754599E");

                    b.HasOne("OriCafe.Models.TaiKhoan", "IdTaiKhoanNavigation")
                        .WithMany("PhanQuyens")
                        .HasForeignKey("IdTaiKhoan")
                        .HasConstraintName("FK__Phan_Quye__id_ta__66603565");

                    b.Navigation("IdQuyenHanNavigation");

                    b.Navigation("IdTaiKhoanNavigation");
                });

            modelBuilder.Entity("OriCafe.Models.SanPham", b =>
                {
                    b.HasOne("OriCafe.Models.LoaiSanPham", "IdLoaiSanPhamNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdLoaiSanPham")
                        .HasConstraintName("FK__San_Pham__id_loa__5535A963");

                    b.HasOne("OriCafe.Models.QuanCaPhe", "IdQuanNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdQuan")
                        .HasConstraintName("FK__San_Pham__id_qua__5441852A");

                    b.Navigation("IdLoaiSanPhamNavigation");

                    b.Navigation("IdQuanNavigation");
                });

            modelBuilder.Entity("OriCafe.Models.TaiKhoan", b =>
                {
                    b.HasOne("OriCafe.Models.NhanVien", "IdNhanVienNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("IdNhanVien")
                        .HasConstraintName("FK__Tai_Khoan__id_nh__619B8048");

                    b.HasOne("OriCafe.Models.QuanCaPhe", "IdQuanNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("IdQuan")
                        .HasConstraintName("FK__Tai_Khoan__id_qu__60A75C0F");

                    b.Navigation("IdNhanVienNavigation");

                    b.Navigation("IdQuanNavigation");
                });

            modelBuilder.Entity("OriCafe.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("OriCafe.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("OriCafe.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("OriCafe.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("OriCafe.Models.QuanCaPhe", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("KhachHangs");

                    b.Navigation("LoaiSanPhams");

                    b.Navigation("NhanViens");

                    b.Navigation("SanPhams");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("OriCafe.Models.QuyenHan", b =>
                {
                    b.Navigation("PhanQuyens");
                });

            modelBuilder.Entity("OriCafe.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("OriCafe.Models.TaiKhoan", b =>
                {
                    b.Navigation("PhanQuyens");
                });
#pragma warning restore 612, 618
        }
    }
}
